# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies
      run: dotnet restore PunkCommandSystem/PunkCommandSystem.sln
    - name: Build
      run: dotnet build PunkCommandSystem/PunkCommandSystem.sln --no-restore --configuration Release
    - name: Test
      run: dotnet test PunkCommandSystem/PunkCommandSystem.sln --no-build --verbosity normal

    - name: Create archive from build artifacts
      run: |
        mkdir -p archive
        cp -r ./PunkCommandSystem/PunkCommandSystem/obj/Release/net48 ./archive/net48
        cp -r ./PunkCommandSystem/PunkCommandSystem/obj/Release/net6.0 ./archive/net6.0
        zip -r PunkCommandRelease.zip archive/
      
    # - name: Move archive to root
    #   run: mv PunkCommandRelease.zip ./
    
    - name: List directory
      run: ls -R

    - name: Create Release
      id: create_release
      uses: softprops/action-gh-release@v1
      with:
        tag_name: v1.0.0 # Replace with your versioning
        name: Release v1.0.0 # Replace with your release name
        draft: false
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.RELEASE_TOKEN }}
    - name: Upload Release Asset
      uses: actions/upload-release-asset@v1
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: PunkCommandRelease.zip # Adjust to your actual asset path
        asset_name: PunkCommandRelease.zip # Name for the asset
        asset_content_type: application/zip

    - name: Clean up
      run: dotnet clean PunkCommandSystem/PunkCommandSystem.sln
